# -*- coding: utf-8 -*-
"""Bitcoin_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZtYltk6gXXRwuF9g4bAuQuU0bVSLRVFD

Importing the modules
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader.data as web

!pip install yfinance  --upgrade --no-cache-dir
import yfinance as yf
yf.pdr_override()

"""Getting the values of BTC_EUR"""

start = '2022-01-28'
bitcoin = web.get_data_yahoo('BTC-EUR', start=start)['Close']
date_bitcoin = bitcoin.index

"""Ploting the graph """

bitcoin.plot()

"""I created the function for calculate the percentage between the days"""

def percentage(yesterday, today):
  value = (today * 100) / yesterday
  if value > 100:
    value = value - 100
    return (f"+{value:.4f}%")
  else:
    value = 100 - value 
    return (f"-{value:.4f}%")

"""Saving the rates in the archer eur_btc_rates.csv"""

import csv
with open('./eur_btc_rates.csv', 'w') as csvfile:
  writer = csv.writer(csvfile, delimiter=',')
  writer.writerow(['Date', 'Close', 'Rate'])
  i = 0
  while i < 10:
    if i !=0:
      writer.writerow([date_bitcoin[i], bitcoin[i], percentage(bitcoin[i-1], bitcoin[i])])
    else:
      writer.writerow([date_bitcoin[i], bitcoin[i], '--'] )
    i += 1

"""Show the rates saved in the archer"""

with open('./eur_btc_rates.csv') as csvfile:
    for x in csv.reader(csvfile):
      print(x)